### ISSUE TITLE
Turn on DAP4 on thredds.ucar.edu

### ISSUE THREAD

**Issue by dopplershift** [Unidata/TdsConfig#10]
Once it's deemed stable.

**Comment by dopplershift** [comment]
See Unidata/thredds#466.

**Comment by lesserwhirls** [comment]
DAP4 only available in TDS 5. Currently not working on thredds-dev, but is turned on.

**Comment by DennisHeimbigner** [comment]
Same problem. It is dying in thredds.core.TdsRequestedDataset.resourceControlOk(TdsRequestedDataset.java:90)
Further investigation shows that the Chronicle Map is failing to get constructed
properly.
