### ISSUE TITLE
Set up Travis to build .zip files

### ISSUE THREAD

**Issue by dopplershift** [Unidata/TdsConfig#19]
- [x] Configure Travis to build the zip files
- [x] Also remove zip files from the repo--and rewrite the history to remove all of the zip files
- [x] Host zip files on S3
- [x] Update fetch script to point at S3

**Comment by jrleeman** [comment]
Should we keep the `fetch.sh` script in each directory or not? It would be fewer changes to the repo if not and seems unnecessary since they will be in the zip.

**Comment by dopplershift** [comment]
I don't think we should be keeping the fetch scripts in the git repository if that's what you're asking.

**Comment by dopplershift** [comment]
Closed since we replaced master branch with #23.
