### ISSUE TITLE
NcML aggs for GOES-16

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/TdsConfig#27]
We should create NcML `joinExisting` time aggregations for some of the GOES-16 collections.

**Comment by lesserwhirls** [comment]
@dopplershift - are we in charge of the directory layout for the GOES 16 data? It'd be nice, in terms of using NcML to do an aggregation, to get rid of the calendar date directory.

**Comment by dopplershift** [comment]
That's completely ours, though I'd like to be certain of getting a useful aggregation before removing it, otherwise sifting through the data would be a real pain.

**Comment by lesserwhirls** [comment]
Actually, we can keep it, but to do the agg we would need to move from:

`${DATA_DIR}/native/satellite/GOES/GOES16/yyyyMMdd/product/channel/*.nc4`

to something like:

`${DATA_DIR}/native/satellite/GOES/GOES16/product/channel/yyyyMMdd/*.nc4`

We can tell the agg to scan a directory and include subdirs, but I don't think we can tell it something like:

`<scan location="${DATA_DIR}/native/satellite/GOES/GOES16/**/CONUS/Channel01/" suffix='.nc4' dateFormatMark="GOES16_#yyyyMMdd_HHmmss" subdirs="true"/>`

Not sure it's smart enough to get the double star in the middle of the path.

**Comment by lesserwhirls** [comment]
Yep, looks like scan does not understand that location expression.

**Comment by dopplershift** [comment]
I can definitely live with that. Into the stack it goes...

**Comment by lesserwhirls** [comment]
I can take care of it when I make a PR for the agg. I can also handle manually moving the "archive" on lead over to the new structure once the pqact is updated (post-PR).

**Comment by dopplershift** [comment]
Ok, let me know when you do. I have a laundry list of things I need to tweak in the script.

**Comment by lesserwhirls** [comment]
Oh - the directory layout is part of ldmalchemy, right?

**Comment by lesserwhirls** [comment]
I'm guessing just changing the order here will work:

https://github.com/Unidata/ldm-alchemy/blob/master/goes-restitch.py#L316-L317

**Comment by lesserwhirls** [comment]
I suppose this one, too?

https://github.com/Unidata/TdsConfig/blob/master/threddsDev/pqacts/pqact.satellite#L112

**Comment by dopplershift** [comment]
That will do it.

**Comment by lesserwhirls** [comment]
I think this can be closed now?

**Comment by dopplershift** [comment]
I think so.
