### ISSUE TITLE
Update catalogs to be compatible with TDS 5.0 NCSS service base

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/TdsConfig#29]
The thredds-test catalogs are inheriting from idd/ thredds/, but should be grabbing from thredds-dev. The big thing is that the `4.6` catalogs still have services explicitly defined in them, and the `ncss` service element is wrong for `5.0` (or not working - see Unidata/thredds#856). The safe thing to do for now is use the standard services capability of 5, in which no service elements are used in the config catalogs (which is what is done in thredds-dev).

**Comment by cwardgar** [comment]
Note that I did similar work for the catalogs in the THREDDS repo in https://github.com/Unidata/thredds/pull/1064. Defaulting to standard services is often useful, but it relies upon knowing the `DataType` or `FeatureType` of datasets in advance. Sometimes that info won't be known, particularly for `datasetScan`. In those cases, I think it's best to define a compound global service (usually named "all") that includes both `ncssGrid` and `ncssPoint` service elements.

**Comment by lesserwhirls** [comment]
Fixed in Unidata/TdsConfig#54
