### ISSUE TITLE
Remove dead datasets

### ISSUE THREAD

**Issue by dopplershift** [Unidata/TdsConfig#77]
With the advent of FV3 GFS, NCEP has also removed some legacy model runs, as noted in [Service Change Notice 19-40](https://www.weather.gov/media/notification/scn19-40gfs_v15_1.pdf). These are:

* ~80km Hawaii (Y?Z??? KWBC)~
* ~47km Alaska  (L?G??? KWBC)~
* 0.5deg Puerto Rico ([LM]?T??? KWBC)
* 95km Alaska ([LM]?H??? KWBC)
* 40km Pacific ([LM]?O???)

 Not sure if we want to wait for these collections to age off the servers before removing them.

**Comment by dopplershift** [comment]
Well, I guess we're not actually filing the Hawaii 80km. OH NOES!

**Comment by dopplershift** [comment]
And not the 47km Alaska

**Comment by lesserwhirls** [comment]
knocked out the remaining three as they have now aged off.
