### ISSUE TITLE
Add new TDWR products

### ISSUE THREAD

**Issue by jarz** [Unidata/TdsConfig#88]
Page 5 of https://www.weather.gov/media/tg/noaaport_radar_products.pdf lists the new 180/DR products that replaced 181.

The data is already available on THREDDS (https://thredds.ucar.edu/thredds/catalog/terminal/level3/TZ0/catalog.html), but IDV can't access it as TZ0/TZ1/TZ2 aren't listed at https://thredds.ucar.edu/thredds/radarServer/terminal/level3/IDD/dataset.xml (referenced by https://thredds.ucar.edu/thredds/radarServer/catalog.xml).

If the fix is as simple as adding entries to a few XML files, I can make a PR. However, I'm unsure what to do with entries for the older products TR0/TR1/TR2.

**Comment by dopplershift** [comment]
Thanks for offering to make the fix! Yes, updating that `dataset.xml` file should take care of it (and fix it for our Python library Siphon). I'd say just replace the TR0, etc. with TZ0, etc. This configuration file is specific to https://thredds.ucar.edu; it doesn't have the TR[012] products available anymore.
